# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Servicios
    url: /#servicios
    weight: 20
  - name: Contacto
    url: /#contacto
    weight: 30
  - name: Portfolio
    url: content/portfolio/portfolio
    weight: 40
 #- parent: Resources
  #  name: Blog
  #  url: blog/
